In [1]:
import numpy as np
import matplotlib.pyplot as plt

# 1. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
arr = np.random.uniform(5, 10, size=(5, 3))
print(arr)

[[8.55895788 8.78007232 7.12997406]
 [6.76311497 9.54489546 8.19606008]
 [7.81981341 8.48873106 7.85315263]
 [6.7723386  7.07485198 5.66189524]
 [7.67101595 9.29484377 8.54973714]]
